// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenantAPI.Data;

#nullable disable

namespace TenantAPI.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TenantAPI.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdApartament")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdApartament = "101",
                            Nombre = "Rafael Tavares Medina",
                            Telefono = "8092457896"
                        },
                        new
                        {
                            Id = 2,
                            IdApartament = "102",
                            Nombre = "Carmen Peña Rodriguez",
                            Telefono = "8095681234"
                        },
                        new
                        {
                            Id = 3,
                            IdApartament = "201",
                            Nombre = "Miguel Santos Jimenez",
                            Telefono = "8298764523"
                        },
                        new
                        {
                            Id = 4,
                            IdApartament = "202",
                            Nombre = "Yolanda Herrera Castillo",
                            Telefono = "8494512367"
                        },
                        new
                        {
                            Id = 5,
                            IdApartament = "301",
                            Nombre = "Franklin Gutierrez Mora",
                            Telefono = "8097835642"
                        },
                        new
                        {
                            Id = 6,
                            IdApartament = "302",
                            Nombre = "Esperanza Vasquez Luna",
                            Telefono = "8292378459"
                        },
                        new
                        {
                            Id = 7,
                            IdApartament = "401",
                            Nombre = "Domingo Pacheco Vargas",
                            Telefono = "8496547832"
                        },
                        new
                        {
                            Id = 8,
                            IdApartament = "402",
                            Nombre = "Miguelina Rosario Diaz",
                            Telefono = "8095432876"
                        },
                        new
                        {
                            Id = 9,
                            IdApartament = "501",
                            Nombre = "Eugenio Mercado Silva",
                            Telefono = "8297654321"
                        },
                        new
                        {
                            Id = 10,
                            IdApartament = "502",
                            Nombre = "Amparo Contreras Mejia",
                            Telefono = "8493876542"
                        });
                });

            modelBuilder.Entity("TenantAPI.Models.ElectricityConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdApartamento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdApartamento");

                    b.ToTable("ElectricityConsumptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadKw = 287.50m,
                            Fecha = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 1
                        },
                        new
                        {
                            Id = 2,
                            CantidadKw = 334.25m,
                            Fecha = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 2
                        },
                        new
                        {
                            Id = 3,
                            CantidadKw = 412.80m,
                            Fecha = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 3
                        },
                        new
                        {
                            Id = 4,
                            CantidadKw = 298.70m,
                            Fecha = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 4
                        },
                        new
                        {
                            Id = 5,
                            CantidadKw = 567.35m,
                            Fecha = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 5
                        },
                        new
                        {
                            Id = 6,
                            CantidadKw = 315.45m,
                            Fecha = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 1
                        },
                        new
                        {
                            Id = 7,
                            CantidadKw = 289.60m,
                            Fecha = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 2
                        },
                        new
                        {
                            Id = 8,
                            CantidadKw = 378.90m,
                            Fecha = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 3
                        },
                        new
                        {
                            Id = 9,
                            CantidadKw = 445.20m,
                            Fecha = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 6
                        },
                        new
                        {
                            Id = 10,
                            CantidadKw = 523.75m,
                            Fecha = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdApartamento = 7
                        });
                });

            modelBuilder.Entity("TenantAPI.Models.ElectricityConsumption", b =>
                {
                    b.HasOne("TenantAPI.Models.Apartment", "Apartment")
                        .WithMany("ElectricityConsumptions")
                        .HasForeignKey("IdApartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("TenantAPI.Models.Apartment", b =>
                {
                    b.Navigation("ElectricityConsumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
